version: '3.8'

services:

  postgres:
    image: postgres:13.0
    container_name: package_db
    volumes:
      - type: volume
        target: /var/lib/postgresql/dataConfig
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"